name: 'Lint Nim with reviewdog'
description: 'Lint Nim with reviewdog on pull requests to improve code review experience.'
author: 'jiro4989'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  ignore_regexp:
    description: |
      Ignore message pattern.
    default: ''
  src:
    description: "flags and args of eslint command. Default: 'src/*.nim'"
    default: 'src/*.nim'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-octagon'
  color: 'blue'
